CREATE TABLE users
(

 USER_ID SERIAL NOT NULL,
 USER_NAME TEXT NOT NULL UNIQUE,
 USER_PASSWORD TEXT NOT NULL,
 USER_ADMIN BOOLEAN NOT NULL DEFAULT FALSE,

 PRIMARY KEY (USER_ID)

);

CREATE TABLE box
(
 BOX_ID SERIAL NOT NULL,
 CONTENTS TEXT
);

CREATE TABLE position
(
 BOX_ID SERIAL REFERENCES box(BOX_ID),
 POSITION integer NOT NULL
);